### ISSUE TITLE
USER STORY: Create User Account

### ISSUE THREAD

**Issue by nacht-falter** [nacht-falter/aikido-course-registration#1]
As a **visitor**, I can **create a user account** so that I can **log in and store my information**.

Acceptance Criteria:
- [ ] There is a Sign Up button accessible from everywhere on the website
- [ ] Upon clicking on the Sign Up button a user registration form is displayed
- [ ] Upon successful registration a new user is created in the database.

Tasks:
- [ ] Add Sign Up button to base template and link to User registration form
- [ ] Create user registration form
- [ ] Create user registration template
